version = 0.1
[default.deploy.parameters]
stack_name = "api-req-lambda-auth"
resolve_s3 = true
s3_prefix = "api-req-lambda-auth"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
